In [1]:
import numpy as np

In [2]:
v = np.linspace(0,10,5)
v

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [3]:
v[1]

2.5

In [4]:
v[:-1]

array([ 0. ,  2.5,  5. ,  7.5])

In [5]:
v[-1]

10.0

In [6]:
v[-1:]

array([ 10.])

In [7]:
v[-1:len(v)]

array([ 10.])

In [8]:
v[-1:3]

array([], dtype=float64)

In [9]:
v[3]

7.5

In [10]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [11]:
vv = np.random.random((5,4))

In [12]:
vv

array([[  2.55065973e-01,   1.45176927e-01,   5.38276031e-01,
          1.81575364e-01],
       [  3.67879408e-01,   2.06144411e-01,   5.87427276e-01,
          3.48873911e-02],
       [  1.46907312e-01,   5.86349991e-01,   3.70743260e-01,
          7.11150045e-01],
       [  9.18223268e-01,   6.03865149e-01,   6.16016252e-04,
          9.39021015e-01],
       [  7.56048319e-01,   6.40816773e-01,   3.44211273e-01,
          4.36839928e-02]])

In [13]:
vv = np.random.random((5,4))

In [14]:
vv

array([[ 0.83835684,  0.93503613,  0.45897207,  0.04577397],
       [ 0.4602612 ,  0.01785836,  0.72768539,  0.8281484 ],
       [ 0.64509261,  0.75756339,  0.02611235,  0.11062125],
       [ 0.13877946,  0.09642665,  0.26798221,  0.84484005],
       [ 0.86798811,  0.05668079,  0.19544314,  0.26229795]])

First index refers to row, second to column

In [15]:
vv[0,0]

0.83835683606391609

In [16]:
vv[0,1]

0.93503612986257978

In [17]:
vv[1,0]

0.46026119586093373

In [18]:
listoflist = [[ 0.83835684,  0.93503613,  0.45897207,  0.04577397],
       [ 0.4602612 ,  0.01785836,  0.72768539,  0.8281484 ],
       [ 0.64509261,  0.75756339,  0.02611235,  0.11062125],
       [ 0.13877946,  0.09642665,  0.26798221,  0.84484005],
       [ 0.86798811,  0.05668079,  0.19544314,  0.26229795]]
listoflist

[[0.83835684, 0.93503613, 0.45897207, 0.04577397],
 [0.4602612, 0.01785836, 0.72768539, 0.8281484],
 [0.64509261, 0.75756339, 0.02611235, 0.11062125],
 [0.13877946, 0.09642665, 0.26798221, 0.84484005],
 [0.86798811, 0.05668079, 0.19544314, 0.26229795]]

In [19]:
listoflist[0][1]

0.93503613

In [20]:
listoflist[1][0]

0.4602612

In [21]:
vv[0:2]

array([[ 0.83835684,  0.93503613,  0.45897207,  0.04577397],
       [ 0.4602612 ,  0.01785836,  0.72768539,  0.8281484 ]])

In [22]:
vv[0:2][0:2]

array([[ 0.83835684,  0.93503613,  0.45897207,  0.04577397],
       [ 0.4602612 ,  0.01785836,  0.72768539,  0.8281484 ]])

In [23]:
vv[0:2,1][0:2,1]

IndexError: too many indices for array

In [24]:
vv[0:2,1]

array([ 0.93503613,  0.01785836])

In [25]:
vv[2:5,1]

array([ 0.75756339,  0.09642665,  0.05668079])

In [26]:
vv

array([[ 0.83835684,  0.93503613,  0.45897207,  0.04577397],
       [ 0.4602612 ,  0.01785836,  0.72768539,  0.8281484 ],
       [ 0.64509261,  0.75756339,  0.02611235,  0.11062125],
       [ 0.13877946,  0.09642665,  0.26798221,  0.84484005],
       [ 0.86798811,  0.05668079,  0.19544314,  0.26229795]])

In [27]:
vv[2:5]

array([[ 0.64509261,  0.75756339,  0.02611235,  0.11062125],
       [ 0.13877946,  0.09642665,  0.26798221,  0.84484005],
       [ 0.86798811,  0.05668079,  0.19544314,  0.26229795]])

In [28]:
vv[2:5,2]

array([ 0.02611235,  0.26798221,  0.19544314])

In [29]:
vv[2:5,0]

array([ 0.64509261,  0.13877946,  0.86798811])

In [30]:
vv[2:5,0:2]

array([[ 0.64509261,  0.75756339],
       [ 0.13877946,  0.09642665],
       [ 0.86798811,  0.05668079]])

In [31]:
vv[2:-1]

array([[ 0.64509261,  0.75756339,  0.02611235,  0.11062125],
       [ 0.13877946,  0.09642665,  0.26798221,  0.84484005]])

In [32]:
vv[1:-1]

array([[ 0.4602612 ,  0.01785836,  0.72768539,  0.8281484 ],
       [ 0.64509261,  0.75756339,  0.02611235,  0.11062125],
       [ 0.13877946,  0.09642665,  0.26798221,  0.84484005]])

In [33]:
vv
vv[2:-1,:]

array([[ 0.64509261,  0.75756339,  0.02611235,  0.11062125],
       [ 0.13877946,  0.09642665,  0.26798221,  0.84484005]])

In [34]:
print(vv)
vv[2:-1,:]

[[ 0.83835684  0.93503613  0.45897207  0.04577397]
 [ 0.4602612   0.01785836  0.72768539  0.8281484 ]
 [ 0.64509261  0.75756339  0.02611235  0.11062125]
 [ 0.13877946  0.09642665  0.26798221  0.84484005]
 [ 0.86798811  0.05668079  0.19544314  0.26229795]]


array([[ 0.64509261,  0.75756339,  0.02611235,  0.11062125],
       [ 0.13877946,  0.09642665,  0.26798221,  0.84484005]])

In [35]:
print(vv)
vv[:,::2]

[[ 0.83835684  0.93503613  0.45897207  0.04577397]
 [ 0.4602612   0.01785836  0.72768539  0.8281484 ]
 [ 0.64509261  0.75756339  0.02611235  0.11062125]
 [ 0.13877946  0.09642665  0.26798221  0.84484005]
 [ 0.86798811  0.05668079  0.19544314  0.26229795]]


array([[ 0.83835684,  0.45897207],
       [ 0.4602612 ,  0.72768539],
       [ 0.64509261,  0.02611235],
       [ 0.13877946,  0.26798221],
       [ 0.86798811,  0.19544314]])