In [1]:
import numpy

In [2]:
import numpy as np
import matplotlib.pyplot as pp

In [3]:
a = np.array([1:5])

SyntaxError: invalid syntax (<ipython-input-3-755366ef4ccb>, line 1)

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
a.dtype

dtype('int32')

In [7]:
a.dtype=np.float64

ValueError: new type not compatible with array.

In [8]:
a.dtype=np.int64

ValueError: new type not compatible with array.

In [9]:
b = array([1,2,3,4,5], dtype=np.float64)

NameError: name 'array' is not defined

In [10]:
b = np.array([1,2,3,4,5], dtype=np.float64)

In [11]:
b.dtype

dtype('float64')

In [12]:
b

array([ 1.,  2.,  3.,  4.,  5.])

In [13]:
a.ndim, a.shape.a.size

AttributeError: 'tuple' object has no attribute 'a'

In [14]:
b.ndim, b.shape, b.size

(1, (5,), 5)

In [15]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)
b

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.]])

In [16]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [17]:
np.zeroes((3,3),'d')

AttributeError: module 'numpy' has no attribute 'zeroes'

In [18]:
np.zeros((3,3),"d")

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [19]:
np.empty((4,4),"D")

array([[  0.00000000e+000 +0.00000000e+000j,
          9.25258057e-312 +0.00000000e+000j,
          0.00000000e+000 +0.00000000e+000j,
          0.00000000e+000 +9.25258055e-312j],
       [  9.25258055e-312 +0.00000000e+000j,
          0.00000000e+000 +9.25258055e-312j,
          9.25258056e-312 +0.00000000e+000j,
          0.00000000e+000 +9.25258055e-312j],
       [  9.25258055e-312 +0.00000000e+000j,
          9.25258055e-312 +0.00000000e+000j,
          9.25258055e-312 +9.25258056e-312j,
          0.00000000e+000 +0.00000000e+000j],
       [  0.00000000e+000 +9.25258058e-312j,
          0.00000000e+000 +9.25258056e-312j,
          0.00000000e+000 +0.00000000e+000j,
          9.25258055e-312 +0.00000000e+000j]])

In [20]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [21]:
c = np.random.standard_normal((2,4))

In [22]:
c

array([[ 0.11441363,  0.96545475, -0.40991329, -0.35358331],
       [-0.46584836, -0.56765595,  0.66822582,  0.73385282]])

In [23]:
c . transpose

<function ndarray.transpose>

In [24]:
c.transpose

<function ndarray.transpose>

In [25]:
c.transpose()

array([[ 0.11441363, -0.46584836],
       [ 0.96545475, -0.56765595],
       [-0.40991329,  0.66822582],
       [-0.35358331,  0.73385282]])

In [26]:
np.save("example2.npy",c)

In [27]:
d = np.load("example2.npy")

In [28]:
d

array([[ 0.11441363,  0.96545475, -0.40991329, -0.35358331],
       [-0.46584836, -0.56765595,  0.66822582,  0.73385282]])

In [29]:
d = transpose(np.load("example2.npy"))

NameError: name 'transpose' is not defined

In [30]:
d = d.transpose(np.load("example2.npy"))

TypeError: only length-1 arrays can be converted to Python scalars

In [31]:
d = c.transpose(np.load("example2.npy"))

TypeError: only length-1 arrays can be converted to Python scalars

In [32]:
d = c.transpose()

In [33]:
d

array([[ 0.11441363, -0.46584836],
       [ 0.96545475, -0.56765595],
       [-0.40991329,  0.66822582],
       [-0.35358331,  0.73385282]])